// <auto-generated />
using System;
using KartOfferService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KartOfferService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OfferDbContext))]
    [Migration("20260726090040_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KartOfferService.Domain.Coupons.Coupon", b =>
                {
                    b.Property<string>("CouponCode")
                        .HasColumnType("text")
                        .HasColumnName("coupon_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int?>("GlobalCap")
                        .HasColumnType("integer")
                        .HasColumnName("global_cap");

                    b.Property<int?>("PerUserCap")
                        .HasColumnType("integer")
                        .HasColumnName("per_user_cap");

                    b.Property<int>("TotalRedemptions")
                        .HasColumnType("integer")
                        .HasColumnName("total_redemptions");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("CouponCode");

                    b.HasIndex("ValidFrom", "ValidUntil")
                        .HasDatabaseName("idx_coupons_validity_window");

                    b.ToTable("coupons", (string)null);
                });

            modelBuilder.Entity("KartOfferService.Domain.Coupons.CouponRedemption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("coupon_code");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_id");

                    b.Property<DateTimeOffset>("RedeemedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redeemed_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset?>("VoidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voided_at");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_coupon_redemptions_order_id");

                    b.HasIndex("CouponCode", "OrderId")
                        .IsUnique()
                        .HasDatabaseName("idx_coupon_redemptions_coupon_order");

                    b.HasIndex("CouponCode", "UserId")
                        .HasDatabaseName("idx_coupon_redemptions_user")
                        .HasFilter("voided_at IS NULL");

                    b.ToTable("coupon_redemptions", (string)null);
                });

            modelBuilder.Entity("KartOfferService.Domain.Pricing.PricingQuote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("pricing_quotes", (string)null);
                });

            modelBuilder.Entity("KartOfferService.Domain.Promotions.PromotionCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("DiscountRule")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("discount_rule");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("promotion_campaigns", (string)null);
                });

            modelBuilder.Entity("KartOfferService.Infrastructure.Persistence.OfferOutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("idx_offer_outbox_unpublished")
                        .HasFilter("published_at IS NULL");

                    b.ToTable("offer_outbox_events", (string)null);
                });

            modelBuilder.Entity("KartOfferService.Infrastructure.Persistence.ProductPriceCacheEntry", b =>
                {
                    b.Property<string>("Sku")
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Sku");

                    b.ToTable("product_price_cache", (string)null);
                });

            modelBuilder.Entity("KartOfferService.Domain.Coupons.CouponRedemption", b =>
                {
                    b.HasOne("KartOfferService.Domain.Coupons.Coupon", null)
                        .WithMany()
                        .HasForeignKey("CouponCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_coupon_redemptions_coupon_code");
                });

            modelBuilder.Entity("KartOfferService.Domain.Pricing.PricingQuote", b =>
                {
                    b.OwnsOne("KartOfferService.Domain.Pricing.Money", "Total", b1 =>
                        {
                            b1.Property<Guid>("PricingQuoteId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("total_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("currency");

                            b1.HasKey("PricingQuoteId");

                            b1.ToTable("pricing_quotes");

                            b1.WithOwner()
                                .HasForeignKey("PricingQuoteId");
                        });

                    b.Navigation("Total")
                        .IsRequired();
                });

            modelBuilder.Entity("KartOfferService.Domain.Promotions.PromotionCampaign", b =>
                {
                    b.OwnsOne("KartOfferService.Domain.Promotions.CampaignWindow", "Window", b1 =>
                        {
                            b1.Property<Guid>("PromotionCampaignId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("EndsAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ends_at");

                            b1.Property<DateTimeOffset>("StartsAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("starts_at");

                            b1.HasKey("PromotionCampaignId");

                            b1.HasIndex("StartsAt", "EndsAt")
                                .HasDatabaseName("idx_promotion_campaigns_window");

                            b1.ToTable("promotion_campaigns");

                            b1.WithOwner()
                                .HasForeignKey("PromotionCampaignId");
                        });

                    b.Navigation("Window")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
